FROM node:20-alpine AS base

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS production

WORKDIR /app

COPY package.json ./
RUN npm install --production

COPY --from=base /app/.next ./.next
COPY --from=base /app/next.config.ts ./
COPY --from=base /app/public ./public

EXPOSE 8000

CMD ["npm", "start"]
